### ISSUE TITLE
Bring back DetectCycleIfLinked?

### ISSUE THREAD

**Issue by selasijean** [wcharczuk/go-incr#10]
A class of self referential formulas like `f(t) = f(t)*g(t) + c` represent actual cycles and DetectCycleIfLinked was used in code to detect these bad formulas, early exit the bind & return useful error messages to the client.

**Comment by wcharczuk** [comment]
That was a casualty of me cleaning up how heights were calculated (which is where we used to do cycle detection). I'll add it back in an upcoming PR that also addresses the observe-ordering issue you've spotted.

**Comment by wcharczuk** [comment]
This is merged!
