### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by selasijean** [wcharczuk/go-incr#22]
Suppose we have a bind that spawns a Map node that relies on a network call that fails occasionally. 
During the stabilization the first time, map node errors and halts stabilization. To retry, we trigger a recompute of the bind's LHS to rerun the rhsFn.

```
func Test_Simple(t *testing.T) {
	g := New(OptGraphClearRecomputeHeapOnError(true))

	var err error
	var cache Incr[*int]
	hasErrored := false
	two := 2

	refresh := Var(g, "refresh")
	r := Bind(g, refresh, func(bs Scope, c string) Incr[*int] {
		if cache != nil {
			return cache
		}

                // replace bs in MapContext and Return with g, and the test still fails.
		cache = MapContext(bs, Return(bs, &two), func(_ context.Context, c *int) (*int, error) {
			out := *c + 1
			if hasErrored {
				return &out, nil
			}
			hasErrored = true
			return nil, fmt.Errorf("deliberate")
		})
		return cache
	})

	o, err := Observe(g, r)
	testutil.NoError(t, err)

	err = g.Stabilize(context.TODO())
	testutil.Error(t, err)

	g.SetStale(refresh) //RETRY

	err = g.Stabilize(context.TODO())
	testutil.NoError(t, err)

	testutil.NotNil(t, o.Value())
	testutil.Equal(t, *o.Value(), 3)
}
```

I believe the test case fails because in the stabilizeFn of bindLeftChange, we invalidate `oldRhsNodes`. But in this test, `oldRhsNodes contains newRhs` so invalidating `oldRhsNodes` invalidates `newRhs` and so we never get to recompute the cached Map node. Also, in `changeParent(child, oldParent, newParent INode)`, if `oldParent == newParent`, we don't add recompute rhs. 

Open questions
- If `b.bind.rhs` is contained in `oldRhsNodes`, is `b.bind.rhs` valid if `b.bind.main` is necessary?
- Is this a bad use of cached nodes/bind invalidation or is this a bug?

**Comment by wcharczuk** [comment]
Thanks for the minimal repro @selasijean! Looking at this there is likely an issue with how the invalidation propagates to the cached result of the bind, last time we messed with this it introduced very severe regressions so it'll take some time to untangle, I'll try and look today.

**Comment by wcharczuk** [comment]
```
func Test_Bind_errors(t *testing.T) {
	ctx := testContext()
	g := New(
		OptGraphTraceEnabled(true),
		OptGraphClearRecomputeHeapOnError(true),
	)

	var err error
	var cached Incr[*int]
	var mapInput Incr[*int]
	hasErrored := false
	two := 2

	refresh := Var(g, "refresh")
	refresh.Node().SetLabel("refresh")
	bind := Bind(g, refresh, func(bs Scope, c string) Incr[*int] {
		if cached != nil {
			return cached
		}
		mapInput = Return(bs, &two)
		// replace bs in MapContext and Return with g, and the test still fails.
		cached = MapContext(bs, mapInput, func(_ context.Context, c *int) (*int, error) {
			out := *c + 1
			if hasErrored {
				return &out, nil
			}
			hasErrored = true
			return nil, fmt.Errorf("deliberate")
		})
		cached.Node().SetLabel("cached")
		return cached
	})
	bind.Node().SetLabel("bind_cache")

	o, err := Observe(g, bind)
	testutil.NoError(t, err)

	err = g.Stabilize(ctx)
	testutil.Error(t, err)

	g.SetStale(mapInput) //RETRY

	err = g.Stabilize(ctx)
	testutil.NoError(t, err)

	testutil.NotNil(t, o.Value())
	testutil.Equal(t, *o.Value(), 3)
}
```

If you tweak your test slightly, and your invalidation targets the map (not the bind!) this works correctly. Going to close as this isn't really a behavior we can change, and there is a workaround.
