### ISSUE TITLE
[API extension] Support MapNIncr.RemoveInput(Incr[A])

### ISSUE THREAD

**Issue by selasijean** [wcharczuk/go-incr#25]
It's almost possible to achieve this with the ExpertGraph.RemoveParent interface but there's no way to modify the list of tracked inputs in MapNIncr externally

```
// need to modify mn.inputs
for index := range mn.inputs {
	values[index] = mn.inputs[index].Value()
}
val, err = mn.fn(ctx, values...)
```

**Comment by wcharczuk** [comment]
Sure, I actually add this in my "mutable" versions of Incr for projects, and it's likely a good idea to have them available in Incr itself, I'll add now.

**Comment by wcharczuk** [comment]
@selasijean this is merged into main, please test it and let me know if it handles what you need it for, and if it looks good i'll mint a new version

**Comment by selasijean** [comment]
@wcharczuk LGTM. Thank you.

Curious, is there a reason we invoke `GraphForNode(mn).SetStale(mn)` for `RemoveInput` but not for `AddInput` too?

**Comment by wcharczuk** [comment]
`GraphForNode(mn).addChild(mn, i)` effectively marks it stale if you look at what that function does (i.e. it adds it to the recompute heap etc.)
