### ISSUE TITLE
Two test cases where bind shows some randomness and then no randomness but always errors out

### ISSUE THREAD

**Issue by selasijean** [wcharczuk/go-incr#4]
Using the usual implemention of `f`

Test 1: Randomness in behavior. If you run it enough times, it will output the right answer. 
```
	a := func(t int) incr.Incr[*int] {
		key := fmt.Sprintf("a-%d", t)
		if _, ok := cache[key]; ok {
			return cache[key]
		}

		r := incr.Bind(context.Background(), fakeFormula, func(c context.Context, formula string) incr.Incr[*int] {
			return incr.Map2(c, f(t), f(t+1), func(l *int, r *int) *int {
				out := *l * *r
				return &out
			})
		})
		cache[key] = r
		return r
	}
        
       
	t.Run("a(t) = f(t) * f(t+1) where f(t) = f(t-1) + 1", func(t *testing.T) {
		o := a(5)

		graph := incr.New()
		incr.Observe(context.Background(), graph, o)

		graph.Stabilize(context.Background())

		assert.NotNil(t, o.Value())

		assert.Equal(t, 21875, *o.Value()) // deliberate failure
	})
```

Test 2: No randomness. It just won't compute - nil pointer exception
```
	b := func(t int) incr.Incr[*int] {
		key := fmt.Sprintf("b-%d", t)
		if _, ok := cache[key]; ok {
			return cache[key]
		}

		r := incr.Bind(context.Background(), fakeFormula, func(c context.Context, formula string) incr.Incr[*int] {
			return incr.Map2(c, f(t), f(t+2), func(l *int, r *int) *int {
				out := *l * *r
				return &out
			})
		})
		cache[key] = r
		return r
	}

	t.Run("b(t) = f(t) * f(t+2) where f(t) = f(t-1) + 1", func(t *testing.T) {
		o := b(5)

		graph := incr.New()
		incr.Observe(context.Background(), graph, o)

		graph.Stabilize(context.Background())

		assert.NotNil(t, o.Value())

		assert.Equal(t, 21875, *o.Value()) // deliberate failure
	})
```

**Comment by wcharczuk** [comment]
I think the root of this is switching to maps to hold the parent+child sets; when you iterate over the maps, the order will be hard to predict. Ideally this doesn't matter, as order only matters for establishing relative heights and then heights take care of any ordering issues, but possibly there is something funky here still

**Comment by wcharczuk** [comment]
related, if you change your `f(...)` in the above to

```go

var f func(context.Context, int) Incr[*int]
	f = func(ctx context.Context, t int) Incr[*int] {
		key := fmt.Sprintf("f-%d", t)
		if _, ok := cache[key]; ok {
			return WithBindScope(ctx, cache[key])
		}
		r := Bind(ctx, fakeFormula, func(ctx context.Context, formula string) Incr[*int] {
			key := fmt.Sprintf("map-f-%d", t)
			if _, ok := cache[key]; ok {
				return WithBindScope(ctx, cache[key])
			}
			if t == 0 {
				out := 0
				r := Return(ctx, &out)
				r.Node().SetLabel("f-0")
				return r
			}
			bindOutput := Map(ctx, f(ctx, t-1), func(r *int) *int {
				out := *r + 1
				return &out
			})
			bindOutput.Node().SetLabel(fmt.Sprintf("map-f-%d", t))
			cache[key] = bindOutput
			return bindOutput
		})
		r.Node().SetLabel(key)
		cache[key] = r
		return r
	}
```

it starts to work; the key is the `return WithBindScope(ctx, cache[key])` line, where we basically jam the innermost bind scope on the returned (cached) nodes. This isn't strictly correct, as those nodes were "created" outside the bind scope, but the tests don't pass otherwise. Still trying to think about how to approach that.

**Comment by selasijean** [comment]
The WithinBindScope addition makes a lot of sense to me. 

I have some thoughts on the cause of this bug visualized [here](https://www.figma.com/file/aWGkezRlGNEqQASSgJeeII/Theory-about-cause-of-bind-bug?type=whiteboard&node-id=0%3A1&t=fyTgOnEp0hn7UxTs-1)

**Comment by selasijean** [comment]
Since unlink kinda represents a "change", maybe in Bind.Unlink we set as stale and add it to the recomputeHeap if it is not orphaned (i.e it has parents) so n.bound is reinitialized.

**Comment by selasijean** [comment]
> Related, if you change your `f(...)` in the above to
> 
> ```go
> var f func(context.Context, int) Incr[*int]
> f = func(ctx context.Context, t int) Incr[*int] {
>     key := fmt.Sprintf("f-%d", t)
>     if _, ok := cache[key]; ok {
> 	    return WithinBindScope(ctx, cache[key])
>     }
>     r := Bind(ctx, fakeFormula, func(ctx context.Context, formula string) Incr[*int] {
> 	    key := fmt.Sprintf("map-f-%d", t)
> 	    if _, ok := cache[key]; ok {
> 		    return WithBindScope(ctx, cache[key])
> 	    }
> 	    if t == 0 {
> 		    out := 0
> 		    r := Return(ctx, &out)
> 		    r.Node().SetLabel("f-0")
> 		    return r
> 	    }
> 	    bindOutput := Map(ctx, f(ctx, t-1), func(r *int) *int {
> 		    out := *r + 1
> 		    return &out
> 	    })
> 	    bindOutput.Node().SetLabel(fmt.Sprintf("map-f-%d", t))
> 	    cache[key] = bindOutput
> 	    return bindOutput
>     })
>     r.Node().SetLabel(key)
>     cache[key] = r
>     return r
> }
> ```
> 
> It starts to work; the key is the `return WithinBindScope(ctx, cache[key])` line, where we basically jam the innermost bind scope on the returned (cached) nodes. This isn't strictly correct, as those nodes were "created" outside the bind scope, but the tests don't pass otherwise. Still trying to think about how to approach that.

@wcharczuk
I thought about it some more and I don't think how I understand how `WithinBindScope` resolved the issue. How does attributing the innermost bind scope to the cache node resolve the bug? I'm trying to build a mental model of what went wrong without `WithinBindScope` and how introducing it resolved the issue.

**Comment by wcharczuk** [comment]
> I thought about it some more and I don't think how I understand how `WithinBindScope` resolved the issue. How does attributing the innermost bind scope to the cache node resolve the bug? I'm trying to build a mental model of what went wrong without `WithinBindScope` and how introducing it resolved the issue.

Honestly, I don't know for sure yet either.

The root of the "problem" that test uncovers is when we bind nodes, specifically once we choose a new right-hand-side of the bind and link it to all the bind's children (or the nodes that take the bind as an input), so that we can forward the stabilized value directly from the rhs node. If the bound node in the first order is a bind, things are easy, we just automatically recurse through it with ` bind::Link`. The case of `f(N>1)` is interesting because there is a map, which then returns a bind. This causes the first "cached" hit for `f(N>1)` not to recurse, and we don't propagate the child forward correctly.

**Comment by wcharczuk** [comment]
So looking at the spec, I think I'm going to phrase the issue here specifically as:

*Without invasive usage of `WithinBindScope(ctx,...)` some call patterns do not resolve in the correct order.*

I'm not sure how to approach this from an API perspective, as it's hard using types to enforce that the user passes the correct context or knows how to structure the calls to good effect.

**Comment by selasijean** [comment]
@wcharczuk 

I finally got a simple repro of this situation I mentioned [here](https://www.figma.com/file/aWGkezRlGNEqQASSgJeeII/Theory-about-cause-of-bind-bug?type=whiteboard&node-id=0%3A1&t=fyTgOnEp0hn7UxTs-1)

```
func Test_Bind(t *testing.T) {
	fakeFormula := Var(Root(), "fakeFormula")
	cache := make(map[string]Incr[*int])

	var m func(bs *BindScope, t int) Incr[*int]
	cut_off := 3
	boundary := 9

        // m(0) = 0; if 3 <= t <=8, m(t) = m(t-1) + 1 else m(t) = m(t-1)
	m = func(bs *BindScope, t int) Incr[*int] {
		key := fmt.Sprintf("m-%d", t)
		if _, ok := cache[key]; ok {
			return WithinBindScope(bs, cache[key])
		}

		r := Bind(bs, fakeFormula, func(bs *BindScope, formula string) Incr[*int] {
			if t == 0 {
				out := 0
				r := Return(bs, &out)
				r.Node().SetLabel("m-0")
				return r
			}

			var bindOutput Incr[*int]
			offset := 1
			if t >= cut_off && t != boundary {
				bindOutput = Map2(bs, m(bs, t-1), Return(bs, &offset), func(l *int, r *int) *int {
					out := *l + *r
					return &out
				})
			} else {
				bindOutput = m(bs, t-1)
			}

			return bindOutput
		})

		r.Node().SetLabel(fmt.Sprintf("m(%d)", t))
		cache[key] = r
		return r
	}

	t.Run("m(0) = 0; if 3 <= t <=8, m(t) = m(t-1) + 1 else m(t) = m(t-1) - fails", func(t *testing.T) {
		graph := New()

		for i := 0; i < 10; i++ {
			o := m(Root(), i)
			_ = Observe(Root(), graph, o)
			ctx := testContext()
			err := graph.Stabilize(WithTracing(ctx))
			testutil.ItsNil(t, err)
			testutil.ItsNotNil(t, o.Value())

			if i >= boundary {
				testutil.ItsEqual(t, 6, *o.Value())
			} else if i >= cut_off {
				testutil.ItsEqual(t, i-2, *o.Value())
			} else {
				testutil.ItsEqual(t, 0, *o.Value())
			}
		}
	})

	cache = make(map[string]Incr[*int]) // clear

	t.Run("m(0) = 0; if 3 <= t <=8, m(t) = m(t-1) + 1 else m(t) = m(t-1) - passes", func(t *testing.T) {
		graph := New()

		observed := make([]ObserveIncr[*int], 10)

		for i := 0; i < 10; i++ {
			o := m(Root(), i)
			obsIncr := Observe(Root(), graph, o)
			observed[i] = obsIncr
		}

		ctx := testContext()
		err := graph.Stabilize(WithTracing(ctx))
		testutil.ItsNil(t, err)

		for i := 0; i < 10; i++ {
			o := observed[i]
			if i >= boundary {
				testutil.ItsEqual(t, 6, *o.Value())
			} else if i >= cut_off {
				testutil.ItsEqual(t, i-2, *o.Value())
			} else {
				testutil.ItsEqual(t, 0, *o.Value())
			}
		}
	})

	cache = make(map[string]Incr[*int]) // clear

	t.Run("m(0) = 0; if 3 <= t <=8, m(t) = m(t-1) + 1 else m(t) = m(t-1) - passes", func(t *testing.T) {
		graph := New()

		o := m(Root(), 9)
		_ = Observe(Root(), graph, o)
		ctx := testContext()
		err := graph.Stabilize(ctx)
		testutil.ItsNil(t, err)
		testutil.ItsNotNil(t, o.Value())

		testutil.ItsEqual(t, 6, *o.Value())
	})
}
```

**Comment by wcharczuk** [comment]
This should be fixed!
